version: '3.9'

services:
  mongodb:
    image: mongo:4
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./dist/mongodb/data:/data/db


# docker-compose up -d start mongodb
# docker-compose down stop mongodb
